;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2023/4/1 10:42:14

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=《新时代人类八百理念》第三版（0 前言）.txt	; 《新时代人类八百理念》第三版 前言
IDH_1001=《新时代人类八百理念》第三版（1-100）.txt	; 《新时代人类八百理念》第三版 1-100
IDH_1002=《新时代人类八百理念》第三版（101-200）.txt	; 《新时代人类八百理念》第三版 101-200
IDH_1003=《新时代人类八百理念》第三版（201-300）.txt	; 《新时代人类八百理念》第三版 201-300
IDH_1004=《新时代人类八百理念》第三版（301-400）.txt	; 《新时代人类八百理念》第三版 301-400
IDH_1005=《新时代人类八百理念》第三版（401-500）.txt	; 《新时代人类八百理念》第三版 401-500
IDH_1006=《新时代人类八百理念》第三版（501-600）.txt	; 《新时代人类八百理念》第三版 501-600
IDH_1007=《新时代人类八百理念》第三版（601-700）.txt	; 《新时代人类八百理念》第三版 601-700
IDH_1008=《新时代人类八百理念》第三版（701-800）.txt	; 《新时代人类八百理念》第三版 701-800
