;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2023/4/1 10:42:14

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 《新时代人类八百理念》第三版 前言 《新时代人类八百理念》第三版（0 前言）.txt
#define IDH_1001	1001	; 《新时代人类八百理念》第三版 1-100 《新时代人类八百理念》第三版（1-100）.txt
#define IDH_1002	1002	; 《新时代人类八百理念》第三版 101-200 《新时代人类八百理念》第三版（101-200）.txt
#define IDH_1003	1003	; 《新时代人类八百理念》第三版 201-300 《新时代人类八百理念》第三版（201-300）.txt
#define IDH_1004	1004	; 《新时代人类八百理念》第三版 301-400 《新时代人类八百理念》第三版（301-400）.txt
#define IDH_1005	1005	; 《新时代人类八百理念》第三版 401-500 《新时代人类八百理念》第三版（401-500）.txt
#define IDH_1006	1006	; 《新时代人类八百理念》第三版 501-600 《新时代人类八百理念》第三版（501-600）.txt
#define IDH_1007	1007	; 《新时代人类八百理念》第三版 601-700 《新时代人类八百理念》第三版（601-700）.txt
#define IDH_1008	1008	; 《新时代人类八百理念》第三版 701-800 《新时代人类八百理念》第三版（701-800）.txt
